server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require&pgbouncer=true
spring.datasource.username=postgres.mwqidsomofhsbsrhddlk
spring.datasource.password=MINTYNEX@PRO1-2026
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.data-source-properties.prepareThreshold=0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.open-in-view=false

jwt.secret=bWludHluZXhTdXBlclNlY3JldEtleUZvckpXVEF1dGgyMDI1TWludHlOZXg=
jwt.access-token-expiry-ms=3600000
jwt.refresh-token-expiry-ms=2592000000

cors.allowed-origins=http://localhost:5500,http://127.0.0.1:5500,http://localhost:3000

logging.level.com.mintynex=DEBUG
logging.level.org.springframework.security=WARN
